feat: add support for vue 3
Grsmto/simplebar pull request #578
Opened 2021-07-09 21:01 UTC by misterupkeep

The existing code is essentially compatible with Vue 3. I've just updated the dependencies.

The dependency on `vue-template-compiler` has been removed, as it targets Vue 2. The upgrade route is to use `@vue/compiler-sfc`, however, as far as I can tell, this is a `rollup-vue-plugin` dep, and it builds just fine without it explicitly listed.

`$listeners` was removed in Vue 3. `$listeners.event` is now `$attrs.onEvent`, so that's been renamed.

2021-07-16 07:04 UTC, letehaha commented
@misterupkeep unfortunately, this will break the Vue2 projects. I think for Vue3 it should require a branch release, and then @Grsmto will need to support two branches at least for next year until Vue 3 will be fully ready for production and people will start using it by default. WDYT?

2021-07-19 20:13 UTC, misterupkeep commented
I'd add another package to the monorepo that would do something like apply a diff patch to `../simplebar-vue` and publish to NPM as `simplebar-vue@next` (or `@beta-2.0`).

2021-09-13 07:43 UTC, webmastervinay commented
Is this package updated to use with Vue 3? I tried simplebar-vue@next and simplebar-vue@beta2-0 but none of it is installing.

2021-09-15 01:17 UTC, getreworked commented
Does anyone have any visibility on this? Does Simplebar support Vue 3? If not, are there plans to support it?

2021-09-15 08:15 UTC, letehaha commented
@webmastervinay @getreworked 
I dunno about if @Grsmto plans to release a new version for Vue3, but if you really need this package in your project, you can simply fork this repository, merge or apply changes from this PR and add your forked repository to your project as a dependency instead of using a simplebar package from npm.

2021-09-15 08:33 UTC, Grsmto commented
Hi,
I'm happy to release a PR but it seems like this one would break Vue 2. Is there no way to support both Vue 2 and 3 without having to maintain 2 packages?

2021-09-15 14:50 UTC, letehaha requested changes

2021-09-15 14:50 UTC, letehaha commented on packages/simplebar-vue/index.vue
>              v-on="{
For Vue 3 versions it is required to use `v-bind`, not `v-on` for such a construction. Check the [docs](https://v3.vuejs.org/guide/migration/listeners-removed.html#listeners-removed) plese

2021-09-15 15:04 UTC, letehaha commented
@Grsmto tbh I'm not sure if it will work, but maybe it's possible to define multiple Vue versions in the `peerDependencies ` and add a small hack to the code, like:

```js
export default {
  // ...
  computed: {
    // ...
    v2Listeners() {
      if (this.$listeners && this.$listeners.scroll) {
        return { scroll:  this.$listeners.scroll }
      }
      return {};
    },
    v3Listeners() {
      if (this.$attrs.onScroll) {
        return { onScroll:  this.$listeners.onScroll }
      }
      return {};
    }
  }
}
```

```html
<div
  class="simplebar-content-wrapper"
  ref="scrollElement"
  v-on="v2Listeners"
  v-bind="v3Listeners"
>
  <div class="simplebar-content" ref="contentElement">
    <slot></slot>
  </div>
</div>
```

Unfortunately, it looks shitty and also I'm not able to test it due to lack of time. In case this approach is better than supporting two versions, then someone might try to implement it.

2021-09-16 16:36 UTC, misterupkeep commented
@letehaha I think the API differences betwen Vue 2 and 3 are deep enough to where the same compiled template code wouldn't work under both runtimes, meaning you'd also have to ship two runtime-selected bundles. 
The way most libraries I've seen have migrated is by publishing an extra `next` version. Seeing as the code is wrapper around a base library, there shouldn't be any messy back-and-forth porting.

2021-09-16 19:17 UTC, letehaha commented
@misterupkeep agreed with you 👍

2021-10-06 22:22 UTC, stafyniaksacha commented
Can we use https://github.com/vueuse/vue-demi instead to overcome the vue2 / vue3 compatibilities issues ?

2022-02-11 03:52 UTC, horans commented
> Vue 3 is now the new default version! [Learn more](https://blog.vuejs.org/posts/vue-3-as-the-new-default.html)

Any plans to archive Vue 2 version, and upgrade to support Vue 3?

2022-11-27 22:54 UTC, Grsmto commented
This has been released in [simplebar-vue@1.7.0](https://github.com/Grsmto/simplebar/releases/tag/simplebar-vue%401.7.0).

2022-11-27 22:54 UTC, closed without merging